### PR TITLE
Pass --target argument to ./configure script

### PR DESCRIPTION
**Pull request by otavio**
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Review by lu-zero — CHANGES_REQUESTED** [review]
target is only useful if you are building compilers and should not be used otherwise, why do you want to pass it? I wouldn't pass it by default.

**Comment by otavio** [comment]
How so? it is used to figure if you are cross-compiling or not. 

I got it working fine for us using this patch. Also, doc says it handles it automatically so it should do.

**Comment by althonos** [comment]
I think in autotools `--host` is used for the platform you want to build to, not `--target` (this is a remnant of autotools being used to compile compilers)

**Comment by otavio** [comment]
Did you try this? here it does work like a charm. 

I think `host` is indeed the new way but this does not fit the crate design. So if we intend to rework this, it'd be a breaking change as we'd need to support `host` and `build` variables.

Considering OpenEmbedded-Core, it also pass those. Check: https://github.com/openembedded/openembedded-core/blob/master/meta/classes/autotools.bbclass#L58-L60

**Comment by lu-zero** [comment]
What are you trying to build? A testcase would be indeed enlightening :)

**Comment by otavio** [comment]
We were building an internal fork of `rusb`. In fact, cross compiling it to Windows.

**Comment by otavio** [comment]
News on this?

**Pull request closed without merging**
